
server:
  port: 8099
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: couponappId
        uri: lb://COUPON-SERVICE
        predicates:
        - Path=/couponapp/**
        
      - id: customerappId
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customerapp/**
        
      - id: productappId
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/productapp/**
        
      - id: orderappId
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/orderapp/**                     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
