version: '3'
services:
  customer:
    image: rajiv2018/ms-customer:1.0
    ports:
      - "8081:8081"
    networks:
      - ms-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

  eureka-server:
    image: rajiv2018/ms-eureka:1.0
    ports:
      - "8761:8761"
    networks:
      - ms-network
networks:
  ms-network:
